apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips-deployment
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - name: trips
        image: hacker4acr.azurecr.io/trips:v2
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: hacker4-azurekeyvault
---
apiVersion: v1
kind: Service
metadata:
  name: trips-service
  namespace: api
spec:
  type: ClusterIP #type can be NodePort / LoadBalancer / ClusterIP
  ports:
  - port: 80
  selector:
    app: trips
